version: '3.8'

services:
  nest-backend:
    container_name: nest-backend
    build:
      context: . # Making a docker image called nest-backend based on Dockerfile
    volumes:
      - ./:/app
    networks:
      - nest-app
    ports:
      - 8000:3000
    environment:
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: me
      POSTGRES_DB: mydb # no seperation
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data # persist data even if container shuts down
    networks:
      - nest-app 
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - nest-app
    restart: always
    depends_on:
      - postgres
    
networks:
  nest-app:
    external: true

volumes:
  db:
  pgadmin:
